### ISSUE TITLE
bug: Unable to resolve codegen and client classes

### ISSUE THREAD

**Issue by onomesotu** [Netflix/dgs-framework#1329]
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue.

## Expected behavior
```
 // GraphQL DGS dependencies
    def dgsVersion = '5.0.5'
    implementation(platform("com.netflix.graphql.dgs:graphql-dgs-platform-dependencies:$dgsVersion"))
    implementation 'com.netflix.graphql.dgs:graphql-dgs-spring-boot-starter'
    implementation 'com.netflix.graphql.dgs:graphql-dgs-extended-scalars'
```

Using DGS 5.0.5 as shown above and codegen plugin 5.1.17, I am able to use the following classes in tests:
```
import com.netflix.graphql.dgs.client.GraphQLClient;
import com.netflix.graphql.dgs.client.GraphQLResponse;
import com.netflix.graphql.dgs.client.codegen.EntitiesGraphQLQuery;
import com.netflix.graphql.dgs.client.codegen.GraphQLQueryRequest;
```

## Actual behavior
After updating DGS to 5.4.0, I am unable to reference the classes above with compilation errors. 
As they cannot be resolved. 

Moving DGS to 5.3.0 fixes 
```
import com.netflix.graphql.dgs.client.GraphQLClient;
import com.netflix.graphql.dgs.client.GraphQLResponse;
```

And I need to revert the plugin down to 5.1.17 to fix 
```
import com.netflix.graphql.dgs.client.codegen.EntitiesGraphQLQuery;
import com.netflix.graphql.dgs.client.codegen.GraphQLQueryRequest;
```

I have read the release docs and can't find anything, in particular, that's causing this issue. 
## Steps to reproduce

_Note: A test case would be highly appreciated, but we understand that's not always possible_

**Comment by benco03** [comment]
This can also be seen using the federation-example project. https://github.com/Netflix/dgs-federation-example/tree/master/reviews-dgs

The EntitiesGraphQLQuery class is not resolvable according to IntelliJ, despite the test being runnable and passing.

Dropping the codegen plugin to 5.1.0 allows IntelliJ to be able to resolve the classes.

![image](https://user-images.githubusercontent.com/2629337/203531205-ab4e90f8-59cc-4b6c-9d4a-f2580d99d16c.png)

**Comment by benco03** [comment]
Turns out this is an issue with IntelliJ's version of Kotlin. 

When viewing the sources, IntelliJ could not decompile because the version of Kotlin used was 1.7, whereas I was on an older version of Kotlin. The code used in DGS 5.1.0 must have been using older versions of Kotlin.

Ensure that you have the latest version of Kotlin by going Preferences -> Languages & Frameworks -> Kotlin and updating to the latest version.

![image](https://user-images.githubusercontent.com/2629337/203536480-39132eb3-ae01-4b13-b82c-383e734af29f.png)
